#=============================================================================
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    automatic_update = false  # `:SPUpdate SpaceVim` for manual update
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer

    colorscheme = "srcery"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    default_indent = 4
    expand_tab = true

    filemanager = "nerdtree"
    # the below will slow down nerdtree
    enable_filetree_gitstatus = true

    project_rooter_patterns = ['.git/',
                               '_darcs/',
                               '.hg/',
                               '.bzr/',
                               '.svn/',
                               '.root/']
    enable_projects_cache = true
    projects_cache_num = 20


    # statusline:nerd fonts required
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    statusline_inactive_separator = "fire"
    statusline_left_sections = [
        'winnr',
        'filename',
        'version control info'
        'search status',
    ]
    statusline_right_sections = [
        'major mode',
        'minor mode lighters'
        'fileformat',
        'input method',
        'cursorpos',
        'percentage'
    ]
    enable_statusline_display_mode = true
    enable_statusline_mode = false

    # snippet_engine = 'ultisnips'

    # Buffer
    buffer_index_type = 4
    enable_os_fileformat_icon = 1
    enable_tabline_filetype_icon = true

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

    # Autocmoplete
    autocomplete_method = "coc"  # Enable COC as the auto-completion engine
    # autocomplete_method = "deoplete"
    # File manager
    filetree_direction = "right"

    # NOTE: the value should be a list, and each item is the name of the plugin.
    #disabled_plugins = ["vim-python-pep8-indent"]

    # Snippet

    # Misc
    # vim_help_language = "cn"

    # Linter
    # lint_engine = "ale"
    lint_engine = "neomake"


# # ==================== User Interface ==================== 
# [[layers]]
#   # For managing workspaces
#   name = "ctrlspace"
#   home-mapping-key = ";"
#   enable-spacevim-styled-keys = false
#   autosave-workspaces = true
#   autoload-workspaces = true

[[layers]]
  # Search index shows the number of occurrences when performing a search via / or ?. SpaceVim integrates the search status nicely by displaying it temporarily when n or N are being pressed. See the 20/22 segment in the screenshot below.
  name = "incsearch"


# ==================== Python IDE ==================== 
[[layers]]
  # Fast syntax highlighting
  name = "treesitter"

[[layers]]
  name = "autocomplete"
  auto_completion_delay = 50
  auto_completion_complete_with_key_sequence = "jj"
  auto_completion_complete_with_key_sequence_delay = 0.1
  autocomplete_parens = true
  auto_completion_return_key_behavior = "complete"  # choose between complete, smart
  auto_completion_tab_key_behavior = "smart"  # choose bewteen smart, complete, cycle


# [[layers]]
  # name = "gtags"
  # gtagslabel = "pygments"


# [[layers]]
    # name = "checkers"
    # lint_on_the_fly = false
    # lint_on_save = false
    # show_cursor_error = false


[[layers]]
  name = "format"
  enable = true

[[layers]]
  # Provide LSP for Python
  name = 'lsp'
  enabled_clients = ['pyright',]

[[layers]]
  # Provide LSP for Bash
  name = "lang#sh"

[[layers]]
  name = "lang#python"
  python_file_head = [
    '""" {Module Name}',
    '',
    'id:            Peter Lee (peter.lee@finclab.com)',
    'last_update:   {Datetime}',
    'type:          lib',
    'sensitivity:   datalab@finclab.com',
    'platform:      any',
    'description:   {Description}',
    '"""'
    '',
    '',
    'if __name__=="__main__":',
    '    print("Done...")',
  ]
  python_interpreter = '/opt/conda/bin/python'
#  enabled_linters = ['pylint']
  enabled_linters = []
  format_on_save = true
  enable_typeinfo = false

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

# [[layers]]
#   name = "lang#html"

# [[layers]]
#   name = "lang#ipynb"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "test"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'github'

[[layers]]
  name = 'git'

#[[layers]]
#  name = "chinese"

[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"

# [[layers]]
# This plugin is not working with py3
#   name = "floobits"


[[layers]]
  name = "ui"
  enable_sidebar = true

[[layers]]
  name = "colorscheme"
  random_theme = false
  frequency = "1h"

# [[layers]]
#   name = "VersionControl"

# [[layers]]
#   name = "denite"

[[layers]]
  # Enable bookmarks
  name = "tools"

# fzf can be installed using: conda install -c conda-forge fzf
[[layers]]
  name = "fzf"

# [[layers]]
#   name = "lang#ipynb"

# [[layers]]
#   # Linters
#   name = "checkers"

[[custom_plugins]]
  name = "christoomey/vim-tmux-navigator"
  merged = false

# [[custom_plugins]]
#   name = "fisadev/vim-isort"
#   merged = false

[[custom_plugins]]
  name = "tmux-plugins/vim-tmux-focus-events"
  merged = false

# [[custom_plugins]]
  # name = "ntpeters/vim-better-whitespace"
  # merged = false
#
# [[custom_plugins]]
    # name = "editorconfig/editorconfig-vim"
    # merged = false
#
# [[custom_plugins]]
  # name = "rkitover/vimpager"
  # merged = false
#
# [[custom_plugins]]
  # name = "wincent/ferret"
  # merged = false
#
# [[custom_plugins]]
  # name = "nelstrom/vim-visual-star-search"
  # merged = false
#
[[custom_plugins]]
  name = "neomake/neomake"
  merged = false

# [[custom_plugins]]
  # name = "tomlion/vim-solidity"
  # merged = false
#
# [[custom_plugins]]
#  This allows jumping to test files
#  Check out: https://www.dev-log.me/Jump_between_test_files_and_implementation_in_Vim/
  # name = 'tpope/vim-projectionist'
  # merged = false
#
# [[custom_plugins]]
  # name = 'tell-k/vim-autoflake'
  # merged = false
#
# [[custom_plugins]]
#   name = 'untitled-ai/jupyter_ascending.vim'
#   merged = false
#
# [[custom_plugins]]
#   name = 'dense-analysis/ale'
#   merged = false
#
[[custom_plugins]]
  name = 'dhruvasagar/vim-table-mode'
  on_ft= "markdown"


# [[custom_plugins]]
#   # required for fzf as it changes working directory to project root
#   name = "airblade/vim-rooter"
#   merged = false

# [[custom_plugins]]
#   name = "vim-airline/vim-airline"
#   merged = false
# 
# [[custom_plugins]]
#   name = "vim-airline/vim-airline-themes"
#   merged = false

# [[custom_plugins]]
#     name = "tmhedberg/SimpylFold"
#     merged = 0
