# ~/.config/starship.toml

# Prompt
# Use custom format
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory (bold white)$username (bold red)$hostname $package $git_branch $git_status $git_commit
[└─>](bold green) """
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
# Disable the blank line at the start of the prompt
add_newline = false

[conda]
format = "[$symbol$environment](bold blue) "
disabled = false

[character]
success_symbol = "[](bold green) "
error_symbol = "[](bold red) "

[directory]
truncation_length = 5
truncate_to_repo = false
#prefix = "in "
style = "bold cyan"
disabled = false

[git_branch]
symbol = "🍣 "
style = "bold yellow"
format = "git [$symbol$branch]($style) "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "⚔️ "
untracked = "🛤️  ×"
stashed = "📦 "
modified = "📝 ×"
staged = "🗃️  ×"
renamed = "📛 ×"
deleted = "🗑️  ×"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
# prefix = ""
# suffix = ""
style = "bright-white"

[hostname]
ssh_only = false
# prefix = "<"
# suffix = ">"
# trim_at = "-"
style = "dimmed white"
format = "on [$hostname](bold red) "
disabled = false

[julia]
symbol = "ஃ "
style = "bold green"
disabled = false

[memory_usage]
threshold = 50
symbol = "🐏"
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
symbol = "👾 "
# symbol = " py "
python_binary = 'python3'
pyenv_version_name = true
pyenv_prefix = "pyenv "

[dotnet]
symbol = " .net "
style = "green"
heuristic = false

[time]
format = '🕙[\[ $time \]]($style) '
use_12hr = true
utc_time_offset = "-5"
style = "bright-white"
time_format = "%T"
disabled = false

[username]
style_root = "black bold"
style_user = "dimmed white"
format = "user [$user]($style) "
disabled = false
show_always = true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"
disabled = true

[[battery.display]]
threshold = 30
style = "bold red"
