#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
FS-Watch - Execute files after file system change.

Module: Data Validation Site
----------------------------

Author: Peter Lee (peter.lee@finclab.com)
Last Update: 2020-12-18

Commandline interface for Building the nginx site for data valiation docs.

The below interfaces are supported:

    >>> ./fswatch   # to start monitoring file system changes

"""
# pylint: disable=global-statement,redefined-builtin

import logging
import os
import shutil

os.environ["DISABLE_PRETTY_TRACEBACK"] = "True"

import time
import typing
from dataclasses import dataclass
from pathlib import Path

import finclab.util.shell
import pandas as pd
from finclab.logger import init_logger
from finclab.tradestation.cli_module.backtest import main as cmd_backtest
from finclab.tradestation.cli_module.util import (get_project_name_from_path,
                                                  get_projects,
                                                  update_requirements)
from finclab.util.shell import print_centered_text
from rich import print
from rich.console import Console
from rich.markdown import Markdown
from simple_parsing import ArgumentParser
from watchdog.events import FileModifiedEvent, PatternMatchingEventHandler
from watchdog.observers import Observer

APP_NAME = "fswatch"
logger = init_logger(f"{APP_NAME}")

param = None  #  Additional parameter, i.e., "--build --verbose --push remote.com"
exec_file = None
cmd = None

counter = 1  # Global counter
COUNTER_TRIGGER_PYTEST = 100  # Every 100 times trigger pytest
# in seconds, minimum number of seconds between running the same script
MIN_WAIT_BETWEEN_FILE_RUN = 1
MIN_WAIT_BETWEEN_PROJECT_RUN = 1

execution_status = {}  # A dict object to store last run times

def get_min_wait(filepath) -> int:
    """Get the minimum wait time between running the same script"""
    if is_strategy_project(filepath):
        return MIN_WAIT_BETWEEN_PROJECT_RUN
    return MIN_WAIT_BETWEEN_FILE_RUN

def discard_event(filepath: typing.Union[str, Path], project:str) -> bool:
    """True to discard events associated with the filepath"""

    # Discard if `backtests` is part of the path
    if "backtests" in str(filepath):
        return True

    # discard temporary file
    if filepath.stem.isnumeric():
        return True

    # discard __pycache__
    if "__pycache__" in str(filepath):
        return True

    # If run recently
    if is_run_recently(filepath=filepath, project=project):
        return True

    return False

def is_strategy_project(path: typing.Union[str, Path]) -> bool:

    # Return True if this is a Strategy for backtesting - if the current folder is a child folder of /lab/paper/ts
    if "/ts/lean" in str(Path(path).absolute()).replace("\\", "/") and path.suffix in [".py"]:
        return True

    return False

def run_pytest():
    """Execute pytest on the current directory"""
    shell_cmd = 'cd (git rev-parse --show-toplevel) && pytest -v -m "not network"'
    os.system(shell_cmd)


def run_backtest(filepath:str, project:str, max_wait=10, show_output=False):
    """Launch backtest on the target file"""
    global execution_status
    finclab.util.shell.print_centered_text(
            text=f"Backtesting strategy --> {project}",
            fill="=",
            extra_space=10,
        )
 
    backtest_output = cmd_backtest(filepath, detach=False, verbose=True)

    if backtest_output is None:
        print(f"The backtest output file cannot be found")
        return

    # wait for 10 seconds until the file shows up
    wait_counter = 0
    while not Path(backtest_output).is_file() and wait_counter < max_wait:
        time.sleep(1)
        wait_counter += 1

    if not Path(backtest_output, "log.txt").is_file():
        print(f"Backtest output file not found: {backtest_output}")

    # Update the end_time
    execution_status[project]["end_time"] = pd.Timestamp.now()

    # Pring location of the backtest output
    finclab.util.shell.print_centered_text(
            text=f"Time elapsed {(execution_status[project]['end_time']-execution_status[project]['end_time']).seconds} seconds. The backtest output available at: {backtest_output}",
        fill="-",
        extra_space=10,
    )
    
    # If show output
    if show_output:
        # Deprecate python module -> use Glow from terminal
        console = Console()
        from finclab.util.chunk import get_chunks

        with open(Path(backtest_output, "log.txt"), encoding="utf-8") as f:
            content = f.readlines()
            chunk_size = shutil.get_terminal_size().lines
            for chunk in get_chunks(data=content, chunk_size=chunk_size):
                markdown = Markdown("\n".join(chunk))
                time.sleep(1)
                console.print(markdown)
    return


def execute_py_file(path: typing.Union[str, Path]):
    """Execute a py file"""


    if cmd is not None:
        # Executing user specified cmd instead
        print("\n\n\n")
        finclab.util.shell.print_centered_text(
            text=f"Begin to execute '{cmd}' ({pd.Timestamp.now().strftime('%Y-%m-%d %H:%m:%S')})",
            fill="-",
            extra_space=5,
        )
        print()
        os.system(cmd)
        return

    if exec_file is not None:
        path = exec_file
        print(path)

    path = Path(path).absolute()

    # if this is a python unit test
    if path.stem.startswith("test_"):
        shell_cmd = f"cd {path.parent} && pytest -v -s -rP {path}"
        os.system(shell_cmd)
        return

    # Other .py files
    param_str = ""
    if param is not None:
        param_str = f" {param}"

    print("\n\n\n")
    finclab.util.shell.print_centered_text(
        text=f"Begin to execute '{str(path)}' ({pd.Timestamp.now().strftime('%Y-%m-%d %H:%m:%S')})",
        fill="-",
        extra_space=5,
    )
    print()
    shell_cmd = f"cd {path.parent} && python {path}{param_str}"
    print(shell_cmd)
    os.system(shell_cmd)


def execute_markdown_file(path: typing.Union[str, Path]):
    """Execute a markdown file"""
    path = Path(path).absolute()
    finclab.util.shell.clear_screen()

    print("\n\n\n")
    finclab.util.shell.print_centered_text(
        text=f"Rendering markdown file: '{str(path)}' ({pd.Timestamp.now().strftime('%Y-%m-%d %H:%m:%S')})",
        fill="-",
        extra_space=5,
    )
    print()

    # Deprecate python module -> use Glow from terminal
    console = Console()
    from finclab.util.chunk import get_chunks

    with open(path, encoding="utf-8") as f:
        content = f.readlines()
        chunk_size = shutil.get_terminal_size().lines
        for chunk in get_chunks(data=content, chunk_size=chunk_size):
            markdown = Markdown("\n".join(chunk))
            time.sleep(1)
            console.print(markdown)

    # Deprecated - use Glow from terminal; cannot control chunksize.
    # shell_cmd = "glow {}".format(path)
    # os.system(shell_cmd)


def on_created(event):
    """Run the task if file is created."""
    print(f"hey, {event.src_path} has been created!")


def on_deleted(event):
    """Run the task if file is deleted."""
    print(f"what the f**k! Someone deleted {event.src_path}!")


def is_run_recently(filepath:str, project: str) -> bool:
    """Return True if the project has been executed within `MIN_WAIT_BETWEEN_FILE_RUN` seconds.
    """
    global execution_status

    project = str(project)
    now = pd.Timestamp.now()

    if project not in execution_status:
        execution_status[project] = {}

    if "end_time" in execution_status[project]:
        end_time = execution_status[project]["end_time"]
        # print("The last run was executed at: {}, {} seconds from now.".format(end_time, (now - end_time).seconds))
        if now - end_time< pd.Timedelta(seconds=get_min_wait(filepath)):
            print( f"Detected new modification on file ({project}) - next auto-execution will take place in {get_min_wait(filepath) - (now-end_time).seconds:,} seconds. Skipped execution...")
            return True

    # if "end_time" not in execution_status[project]:
    #     # Still running the 1st time
    #     print(f"Detected new modification on project ({project}) but it is still running the 1st time...")
    #     from pprint import pprint
    #     pprint(execution_status)
    #     return False

    return False


def on_modified(event):
    """Run the task if file is modified."""
    global counter
    global execution_status

    filepath = Path(event.src_path).absolute()

    if Path("/lab/paper/ts/lean") in filepath.parents:
        # This is a Strategy for backtesting
        # Obtain the strategy name
        project = get_project_name_from_path(filepath)
    else:
        project = str(filepath.absolute())

    start_time = pd.Timestamp.now()

    if discard_event(filepath=filepath, project=project):
        return

    global execution_status

    if not filepath.is_file():
        return

    # Identify if this is a Strategy for backtesting - if the current folder is a child folder of /lab/paper/ts
    if is_strategy_project(filepath):
        run_backtest(filepath=filepath, project=project)
    elif filepath.suffix in [".py"]:
        execute_py_file(path=filepath)
    elif filepath.name in ["cli"]:
        execute_py_file(path=filepath)
    elif filepath.suffix in [".md"]:
        execute_markdown_file(path=filepath)
    else:
        print(f"A non-monitored file ({event.src_path}) has been modified...")
        return

    print()

    # Launch pytest counter
    counter += 1

    if counter > COUNTER_TRIGGER_PYTEST:
        run_pytest()
        counter = 1

    # Update execution time
    end_time = pd.Timestamp.now()
    text_done = "Execution completed (time elapsed: {duration}). {cnt:,} more runs until pytest.".format(
        duration=end_time - start_time, cnt=COUNTER_TRIGGER_PYTEST - counter + 1
    )
    execution_status[project]["end_time"] = end_time

    # Update the start_time
    execution_status[project]["start_time"] = start_time

    finclab.util.shell.print_centered_text(
        text=text_done,
        fill=None,
    )


def on_moved(event):
    """Run the task if file is moved."""
    print(f"ok ok ok, someone moved {event.src_path} to {event.dest_path}")


def fswatch(
    path: typing.Union[str, Path] = Path.cwd().absolute(),
):
    """Watch for file system changes.
    Parameters
    ----------
        path: the path of the folder to watch for any file events
        exec: upon any file changes in the folder, exec only this filepath
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    event_handler = FileModifiedEvent(path)

    # Event handler
    patterns = "*"
    ignore_patterns = [
        "*/*.json",
        "*/*@neomake*",
        "*.py.*.py",
        "*__pycache__*",
        "*cli.*",
        "*.sync.*",
    ]
    ignore_directories = True
    case_sensitive = True
    event_handler = PatternMatchingEventHandler(
        patterns, ignore_patterns, ignore_directories, case_sensitive
    )

    # Assign dispatcher
    # event_handler.on_created = on_created
    # event_handler.on_deleted = on_deleted
    event_handler.on_modified = on_modified
    # event_handler.on_moved = on_moved

    # Observer will monitor our filesystem, looking for changes that will be handled by the event handler.
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)

    # Kick off the process
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
        observer.join()
    finally:
        observer.stop()
        observer.join()


def refresh_screen():
    """Clean screen and display menu heading."""
    finclab.util.shell.clear_screen()
    finclab.util.shell.print_welcome_screen(
        "Welcome to FS Watchdog",
        [
            "Execute files on change",
            ":pile_of_poo:",
            "Author: Peter Lee",
            "Today: {}".format(pd.Timestamp.now().strftime("%Y-%m-%d")),
        ],
    )


@dataclass
class MainMenu:
    """FSWatch Main Menu -- Files are executed upon changes of files."""

    folder: typing.Union[str, Path] = str(
        Path("/lab/paper").absolute()
    )  # location of filepath to monitor
    exec_file: typing.Optional[
        str
    ] = None  # upon any file changes in the folder, exec only this filepath
    param: typing.Optional[
        str
    ] = None  # Additional parameter, i.e., "build verbose push remote.com"
    cmd: typing.Optional[
        str
    ] = None  # Specify a full command to be executed upon observing any changes

    def execute(self):
        """Main entry point"""
        # Parse Variables
        self.folder = Path(self.folder)
        refresh_screen()
        print(f"Watching folder: {self.folder}")
        global param
        if self.param is not None:
            param = self.param
        global exec_file
        if self.exec_file is not None:
            exec_file = self.exec_file
        global cmd
        if self.cmd is not None:
            cmd = self.cmd

        fswatch(self.folder)


parser = ArgumentParser()
parser.add_arguments(MainMenu, dest="FSWatchCLI")

if __name__ == "__main__":
    args = parser.parse_args()
    FSWatchCLI: MainMenu = args.FSWatchCLI
    FSWatchCLI.execute()
