#!/usr/bin/env python
""" CLI Installation for Zsh

id:            Peter Lee (peter.lee@finclab.com)
last_update:   2022-03-28 09:31:43 EDT
type:          lib
sensitivity:   datalab@finclab.com
platform:      any
description:   This module intends for reinstalling Zsh in terminal environment.
"""

import os
import os.path
import shutil
import typing
from dataclasses import dataclass
from pathlib import Path

import finclab.cli.build
import finclab.cli.build.util
import finclab.config.helper
import finclab.config.main
import finclab.io.file
from finclab.logger import init_logger
from simple_parsing import ArgumentParser

app_name = "Zsh"
logger = init_logger("Install.Files")

DIR_DOTFILES = Path(Path.home(), ".files")

# SYMLINKS
SYMLINKS = {
    # zshrc
    Path(Path.home(), ".zshrc"): Path(DIR_DOTFILES, "zsh", "zshrc"),
    # zpreztorc
    Path(Path.home(), ".zpreztorc"): Path(DIR_DOTFILES, "zsh", "zpreztorc"),
    # starship
    Path(Path.home(), ".config", "starship.toml"): Path(DIR_DOTFILES, "starship", "starship.toml"),

    # Other zprezto runcoms
    Path(Path.home(), ".zlogin"): Path(Path.home(), ".zprezto", "runcoms", "zlogin"),
    Path(Path.home(), ".zlogout"): Path(Path.home(), ".zprezto", "runcoms", "zlogout"),
    Path(Path.home(), ".zprofile"): Path(Path.home(), ".zprezto", "runcoms", "zprofile"),
    Path(Path.home(), ".zshenv"): Path(Path.home(), ".zprezto", "runcoms", "zshenv"),
}


def update_symlink():
    """Re-link the config files from dotfiles repo."""
    # Connect to zprezto runcoms
    # Create symlink to .files folder
    for nonexist, exist in SYMLINKS.items():
        print(f"Creating symlink from {exist} to {nonexist}...")
        finclab.io.file.update_symlink(nonexist, exist)


def force_install():
    """For fresh installation (the 1st time)."""
    # Remove the current config
    if Path(Path.home(), ".config/lvim").is_dir():
        shutil.rmtree(Path(Path.home(), ".config/lvim"))
    if not Path(Path.home(), ".config", "lvim").exists():
        Path(Path.home(), ".config", "lvim").mkdir(parents=True)

    # Install LunarVim - Rolling Branch
    cmd = "LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh) -y"
    os.system(f'/bin/bash -c "{cmd}"')


@dataclass
class Install:
    """CLI Tool to Configure / Install Zsh

    Usage
    -----
    ```bash
        # Install
        >>> ts cli install

        # Reinstall
        >>> ts cli install --force
    ```
    """

    force: bool = False  # True force reinstall the NeoVim

    def execute(self):
        """Execute"""
        print(f"Welcome to {app_name} Installation Script...")
        if self.force:
            raise ValueError("Sorry not done...")
            force_install()
        update_symlink()


@dataclass
class Update:
    """CLI Tool to Update Zsh to latest

    Usage
    -----
    ```bash
        # Update to latest stable
        >>> ts cli update

        # Update to latest edge
        >>> ts cli update --edge
    ```
    """

    edge: bool = False  # True Update to the latest edge release (nonstable)

    def execute(self):
        """Execute"""
        print("Updating zprezto")
        cmd = '''
            # Update zprezto
            cd ~/.zprezto
            git pull
            git submodule sync --recursive
            git submodule update --init --recursive
            '''
        os.system(cmd)

        print("Updating starship")
        cmd = '''
        # This will install/update the latest version
        cargo install starship
        '''
        os.system(cmd)

        print("Update zsh-z - a plugin for zprezto")
        cmd = '''
        # Orig install: git clone https://github.com/agkozak/zsh-z.git ~/.zprezto-contrib/zsh-z
        cd ~/.zprezto-contrib/zsh-z
        git pull
        git submodule sync --recursive
        git submodule update --init --recursive
        '''
        os.system(cmd)


@dataclass
class MainMenu:
    """Zsh Installation CLI Main Menu"""

    command: typing.Union[Install, Update]

    def execute(self):
        """Main entry point"""
        return self.command.execute()


parser = ArgumentParser()
parser.add_arguments(MainMenu, dest="PodBuilderCLI")

if __name__ == "__main__":
    args = parser.parse_args()
    PodBuilderCLI: MainMenu = args.PodBuilderCLI

    PodBuilderCLI.execute()
