#! /usr/bin/env zsh

# -------------------========================================------------------- #
#                                                                                #
#                                                                                #
#  ███████╗██╗      █████╗ ██████╗     ███████╗███████╗██╗  ██╗██████╗  ██████╗  #
#  ██╔════╝██║     ██╔══██╗██╔══██╗    ╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝  #
#  █████╗  ██║     ███████║██████╔╝      ███╔╝ ███████╗███████║██████╔╝██║       #
#  ██╔══╝  ██║     ██╔══██║██╔══██╗     ███╔╝  ╚════██║██╔══██║██╔══██╗██║       #
#  ██║     ███████╗██║  ██║██████╔╝    ███████╗███████║██║  ██║██║  ██║╚██████╗  #
#  ╚═╝     ╚══════╝╚═╝  ╚═╝╚═════╝     ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝  #
#                                                                                #
# Author: Peter Lee (peter.lee@finclab.com)                                      #
# Last Update: 2022-May                                                          #

# -------------------========================================------------------- #


# ------------------================== Helper Functions ==================------------------ #
# ------------------================== zoxide:: replacement of `cd`  ==================------------------ #
eval "$(zoxide init zsh)"

# setenv is compatible in both Zsh and Fish
function setenv() { export "$1=$2"; }

export TZ=America/New_York
# export TERM=xterm-256color
export TERM=tmux-256color

# Set zsh function path
fpath=( /usr/local/bin /lab/lib/finclab/sh/zsh "${fpath[@]}")
# autoload -Uz parse_yml

# Enter the most recently modified directories
alias latest='cd $(find . -maxdepth 1 -type d -printf "%f\n" | sort | tail -n1)'

# check of os type
if [[ "$(uname)" == "Darwin" ]]; then
    # Do something under Mac OS X platform
    export os_type='mac'
    # Ensure more number of files to be opened
    ulimit -S -n 200048
    # shortcut for Neovide
    alias gvim='neovide --remote-tcp=10.1.1.100:60001 --nofork --noidle --maximized --multigrid'
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
    # Do something under GNU/Linux platform
    export os_type='linux'
elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]]; then
    # Do something under 32 bits Windows NT platform
    export os_type='windows'
elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]]; then
    # Do something under 64 bits Windows NT platform
    export os_type='windows'
fi


# ------------------================== Rust ==================------------------ #
## Source Cargo
if [[ ( -f "$HOME/.cargo/env" ) ]]; then
  . "$HOME/.cargo/env"
fi


# ------------------================== Python ==================------------------ #
# Trigger conda environment
dirs=( '/opt/conda' \
       '/opt/anaconda' )
for folderpath in $dirs; do 
    if [ -d $folderpath ]; then
       . "$folderpath/etc/profile.d/conda.sh"
    fi
done

# repos=("finclab" \
#        "datalab" \
#        "datalab_utilities" \
#        "execengines_aquamesh" \
#        "ts" \
#        "winclient")

# for repo in $repos; do 
#     if [ -d ${HOME}/lab/paper/${repo} ]; then
#         export PYTHONPATH=${HOME}/lab/paper/${repo}:${PYTHONPATH}
#         echo "Python Path - included additional source lib ${HOME}/lab/paper/${repo}"
#     else
#         if [ -d /lab/${repo} ]; then
#             export PYTHONPATH="/lab/${repo}:${PYTHONPATH}"
#             echo "Python Path - included additional source lib /lab/${repo}"
#         fi
#     fi
# done


# ------------------================== Env Variables ==================------------------ #
# Grab env variables
if [ -f "${HOME}/.lab/labenv.yml" ]; then
    echo "Bash ENV - Extracted config from 'labenv' (${HOME}/.lab/labenv.yml)..."
    . parse_yml "${HOME}/.lab/labenv.yml" >/dev/null
    # for package in ${HOME}/.lab/*.yml ; do
    for package in "${HOME}/.lab/finclab.yml" "${HOME}/.lab/datastore.yml" "${HOME}/.lab/tradestation.yml" "${HOME}/.lab/github.yml" ; do
        test "$package" = "${HOME}/.lab/labenv.yml" && continue
        filestem=$(basename -s .yml $package)
        echo "Bash ENV - Extracted config from '${filestem}' (${package})..."
        . parse_yml "${package}" "${filestem}_" >/dev/null
    done
fi


## ------------------================== Themes ==================------------------ #

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Starfish theme
# Ensure zsh tab-complete prompts works correctly
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
eval "$(starship init zsh)"

# ------------------================== Functions ==================------------------ #
files=( ~/.files/zsh/zalias \
       /lab/lib/finclab/sh/zsh/utils \
      )
for file in $files; do 
    if [ -f $file ]; then
       source $file
    fi
done

# After `brew install curl` in mac os
if [ -f /usr/local/opt/curl/bin/curl ]; then
    export PATH="/usr/local/opt/curl/bin:$PATH"
fi

# ------------------================== General Settings ==================------------------ #
# Zsh-VI-Mode changing the escape key to `kj`
# ZVM_VI_ESCAPE_BINDKEY=kj
# ZVM_VI_INSERT_ESCAPE_BINDKEY=kj
# ZVM_VI_VISUAL_ESCAPE_BINDKEY=kj
# ZVM_VI_OPPEND_ESCAPE_BINDKEY=kj
# Change to Zsh's default readkey engine
ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_ZLE
zvm_bindkey viins '^H' up-line-or-history
zvm_bindkey viins '^L' down-line-or-history

export EDITOR='nvim'
export VISUAL='nvim'

# Ensure correct alias of vim to `nvim` or `nvr` (if running inside nvim)
if [[ ${#${NVIM_LISTEN_ADDRESS}} -eq 0 ]]; then
    # echo "Running in SHELL: ${#${NVIM_LISTEN_ADDRESS}} - $NVIM_LISTEN_ADDRESS"
    alias v='nvim'
    alias vim='nvim'
else
    # echo "Running inside NVIM: ${#${NVIM_LISTEN_ADDRESS}} - $NVIM_LISTEN_ADDRESS"
    alias v='nvr -cc "ToggleTerm || vsplit" -c "ToggleTerm" --remote-silent'
    alias vim='nvr -cc "ToggleTerm || vsplit" -c "ToggleTerm" --remote-silent'
fi

# Configure pager 'less'
export MANPAGER='less -s -M +Gg'
manp() {
	LESS_TERMCAP_md=$'\e[00;36m' \
	LESS_TERMCAP_me=$'\e[0m' \
	LESS_TERMCAP_se=$'\e[0m' \
	LESS_TERMCAP_so=$'\e[01;31m' \
	LESS_TERMCAP_ue=$'\e[0m' \
	LESS_TERMCAP_us=$'\e[00;33m' \
	command man "$@"
}

export HOUSTON_URL=http://10.1.1.100:1969
export BBG_ROOT=/lab/data/samba/tradestation/data/interim/xbbg

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD
# Now we can pipe to multiple outputs!
setopt MULTIOS
# This makes cd=pushd; this option you can use something like cd -5 to get back to the 5th directory you've visited.
setopt AUTO_PUSHD
# This will use named dirs when possible
setopt AUTO_NAME_DIRS
# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS
# No more annoying pushd messages...
# setopt PUSHD_SILENT
# blank pushd goes to home
setopt PUSHD_TO_HOME
# this will ignore multiple directories for the stack.  Useful?  I dunno.
setopt PUSHD_IGNORE_DUPS
# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT
# use magic (this is default, but it can't hurt!)
setopt ZLE
setopt NO_HUP
setopt IGNORE_EOF
# If I could disable Ctrl-s completely I would!
setopt NO_FLOW_CONTROL
# Keep echo "station" > station from clobbering station
setopt NO_CLOBBER
# Case insensitive globbing
setopt NO_CASE_GLOB
# Be Reasonable!
setopt NUMERIC_GLOB_SORT
setopt EXTENDED_GLOB
# hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RC_EXPAND_PARAM
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'


# ------------------================== Bindings ==================------------------ #
# export KEYTIMEOUT=20
bindkey -s '^o' 'vim $(fzf)^M'

# autocomplete CTRL-; to move to the end of auto-suggestions
bindkey '^f' end-of-line
bindkey '^j' end-of-line
# bindkey '^l' forward-word
# bindkey '^h' backward-word

# Make home and end to work
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help

# oh wow!  This is killer...  try it!
bindkey -M vicmd "q" push-line

# it's like, space AND completion.  Gnarlbot.
# bindkey -M viins ' ' magic-space

# Navigate in tab autocomplete menu
# bindkey -M menuselect 'h' vi-backward-char
# bindkey -M menuselect 'k' vi-up-line-or-history
# bindkey -M menuselect 'l' vi-forward-char
# bindkey -M menuselect 'j' vi-down-line-or-history

# Edit line in vim
autoload edit-command-line; zle -N edit-command-line
bindkey '^x' edit-command-line


# ------------------================== Conda Activation ==================------------------ #

# Default repos -- integrate the variable of default environment
unset PYTHONPATH

# Activate corresponding environment
if [ -f /opt/conda/envs/prod/bin/python ]; then
    conda activate prod
    export PYTHONPATH=/lab/lib:~/lab/lib:$(find /opt/conda/envs/prod -type d -path "*/python*/site-packages" | head -n 1)
    echo "Activated env PROD: $(python --version) @ $(which python)" | lolcat
elif [ -f /opt/conda/envs/paper/bin/python ]; then
    conda activate paper
    export PYTHONPATH=/lab/lib:~/lab/lib:$(find /opt/conda/envs/paper -type d -path "*/python*/site-packages" | head -n 1)
    echo "Activated env PAPER: $(python --version) @ $(which python)" | lolcat
fi

# Config for jupyter_ascending
export JUPYTER_ASCENDING_EXECUTE_PORT=8888

# ------------------================== Custom Modules ==================------------------ #
PROJECT_PATHS=( /lab/paper ~ ~/lean )
if [ -f ~/.files/zsh/modules/project_jump.zsh ]; then
    source ~/.files/zsh/modules/project_jump.zsh
fi

# ------------------================== Login script ==================------------------ #
# Cow-spoken fortunes every time you open a terminal
function cowsayfortune {
    NUMOFCOWS=`cowsay -l | tail -n +2 | wc -w`
    WHICHCOW=$((RANDOM%$NUMOFCOWS+1))
    THISCOW=`cowsay -l | tail -n +2 | sed -e 's/\ /\'$'\n/g' | sed $WHICHCOW'q;d'`

    #echo "Selected cow: ${THISCOW}, from ${WHICHCOW}"
    fortune | cowsay -f $THISCOW -W 100
}
cowsayfortune | lolcat --spread 1.0


