#!/usr/bin/env python
""" CLI Installation for NeoVim

id:            Peter Lee (peter.lee@finclab.com)
last_update:   2022-03-28 09:31:43 EDT
type:          lib
sensitivity:   datalab@finclab.com
platform:      any
description:   This module intends for reinstalling NeoVim in terminal environment.
"""

import os
import os.path
import shutil
import typing
from dataclasses import dataclass
from pathlib import Path

import finclab.cli.build
import finclab.cli.build.util
import finclab.config.helper
import finclab.config.main
import finclab.io.file
from finclab.logger import init_logger
from simple_parsing import ArgumentParser

app_name = "NeoVim"
logger = init_logger("Install.Files")

DIR_DOTFILES = Path(Path.home(), ".files")

# SYMLINKS
SYMLINKS = {
    # AstroNvim
    Path(Path.home(), ".config", "nvim", "lua", "user"): Path("/lab/paper/astronvim"),
    # Spell dicts
    Path(Path.home(), ".config", "nvim", "spell"): Path(
        DIR_DOTFILES, "neovim", "spell"
    ),
    # Code skeleton
    Path(Path.home(), ".config", "nvim", "skeleton"): Path(
        DIR_DOTFILES, "neovim", "skeleton"
    ),
    # LunarVim user config
    # Path(Path.home(), ".config", "lvim", "config.lua"): Path( DIR_DOTFILES, "neovim", "lvim", "config.lua"),
    # Additional config dir
    # Path(Path.home(), ".config", "lvim", "vimscript"): Path( DIR_DOTFILES, "neovim", "lvim", "vimscript"),
    # Path(Path.home(), ".config", "lvim", "lua"): Path( DIR_DOTFILES, "neovim", "lvim", "lua"),
    # Path(Path.home(), ".local", "share", "lunarvim", "lvim", "lua", "config"): Path( DIR_DOTFILES, "neovim", "lvim", "lua", "config"),
    # SpaceVim user folder
    # Path(Path.home(), ".SpaceVim.d"): Path(DIR_DOTFILES, "neovim", ".SpaceVim.d"),
    # pylintrc
    Path(Path.home(), ".pylintrc"): Path(DIR_DOTFILES, "neovim", ".pylintrc"),
    # pydocstyle
    Path(Path.home(), ".config", "pycodestyle"): Path(
        DIR_DOTFILES, "neovim", "pycodestyle"
    ),
}


def update_symlink():
    """Re-link the config files from dotfiles repo."""
    # Ensure the data folders exist
    for nonexist, exist in SYMLINKS.items():
        print(f"Creating symlink from {exist} to {nonexist}...")
        finclab.io.file.update_symlink(nonexist, exist)


def force_install():
    """For fresh installation (the 1st time)."""
    # AstroNvim
    # Clean up existing cache
    folders = ["~/.config/nvim", "~/.config/nvim/lua/user", "~/.local/share/nvim/site"]
    for folder in folders:
        if Path(folder).is_dir():
            # Remove this folder
            shutil.rmtree(Path(folder))
    cmd = "git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim"
    os.system(cmd)
    cmd = "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
    os.system(cmd)

    # Remove the current config
    # if Path(Path.home(), ".config/lvim").is_dir():
    #     shutil.rmtree(Path(Path.home(), ".config/lvim"))
    # if not Path(Path.home(), ".config", "lvim").exists():
    #     Path(Path.home(), ".config", "lvim").mkdir(parents=True)

    # # Install LunarVim - Rolling Branch
    # cmd = "LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh) -y"
    # os.system(f'/bin/bash -c "{cmd}"')


@dataclass
class Install:
    """CLI Tool to Configure / Install Neovim

    Usage
    -----
    ```bash
        # Install
        >>> ts cli install

        # Reinstall
        >>> ts cli install --force
    ```
    """

    force: bool = False  # True force reinstall the NeoVim

    def execute(self):
        """Execute"""
        print(f"Welcome to {app_name} Installation Script...")
        if self.force:
            force_install()
        update_symlink()


@dataclass
class Update:
    """CLI Tool to Update Neovim to latest

    Usage
    -----
    ```bash
        # Update to latest stable
        >>> ts cli update

        # Update to latest edge
        >>> ts cli update --edge
    ```
    """

    edge: bool = False  # True Update to the latest edge release (nonstable)

    def execute(self):
        """Execute"""
        if self.edge:
            raise ValueError("@todo sorry not-supported yet.")
        raise ValueError("@todo sorry update is not-supported yet.")


@dataclass
class MainMenu:
    """NeoVim Installation CLI Main Menu"""

    command: typing.Union[Install, Update]

    def execute(self):
        """Main entry point"""
        return self.command.execute()


parser = ArgumentParser()
parser.add_arguments(MainMenu, dest="PodBuilderCLI")

if __name__ == "__main__":
    args = parser.parse_args()
    PodBuilderCLI: MainMenu = args.PodBuilderCLI

    PodBuilderCLI.execute()
